name: tripx_frontend
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  collection: ^1.18.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  cached_network_image: ^3.3.1
  
  # STATE MANAGEMENT
  provider: ^6.1.5

  # NETWORKING
  dio: ^5.4.3+1

  # SECURE STORAGE
  flutter_secure_storage: ^9.2.2

  # UTILITIES
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  fl_chart: ^0.68.0
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2

  # JSON SERIALIZATION
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3 

  # CODE GENERATION
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

# This override solves the conflict between speech_to_text and flutter_secure_storage
dependency_overrides:
  js: ^0.7.1

flutter:
  uses-material-design: true