name: tripx
description: "A Flutter travel planning app that helps users organize their trips easily with features like destination ideas, trip planner, daily schedule, packing list, travel notes, and expense tracker."

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2              # For API calls
  flutter_dotenv: ^5.2.1    # For securely loading API keys
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  provider: ^6.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  fl_chart: ^0.68.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.0
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  #   - assets/data/
  #   - .env   # 👈 Required for flutter_dotenv to load API keys

  # Fonts (optional, you can uncomment if needed)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700