
const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Destination = require('./src/models/destination.model');

// Override collection name to 'Destination Ideas'
Destination.collection.name = 'Destination Ideas';

dotenv.config();

const destinations = [
  // --- INDIAN DESTINATIONS (DOMESTIC) ---
  {
    name: 'Goa',
    country: 'India',
    description: 'Experience vibrant beaches, lively nightlife, and Portuguese architecture. Perfect for a warm winter getaway.',
    imageUrl: 'https://holidayguidemagazine.com/wp-content/uploads/2022/06/goa-Holiday-Guide-India.jpeg',
    category: ['Beach'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Jaipur',
    country: 'India',
    description: 'Explore the Pink City\'s majestic forts, palaces, and vibrant markets under the pleasant winter sun.',
    imageUrl: 'https://tse1.mm.bing.net/th/id/OIP.m775QwB4fCDsPOrHdB-wMgHaEA?w=1070&h=579&rs=1&pid=ImgDetMain&o=7&rm=3',
    category: ['Cultural', 'Historical', 'City'],
    bestSeason: ['Winter', 'Autumn'],
    isDomestic: true,
  },
  {
    name: 'Kerala Backwaters',
    country: 'India',
    description: 'Cruise through serene backwaters, witness traditional houseboat living, and enjoy Ayurvedic treatments.',
    imageUrl: 'https://thumbs.dreamstime.com/b/houseboat-kerala-backwaters-india-vintage-retro-hipster-style-travel-image-travel-tourism-background-38719864.jpg',
    category: ['Nature'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Ranthambore',
    country: 'India',
    description: 'Spot majestic Bengal tigers and other wildlife in this famous national park during comfortable winter weather.',
    imageUrl: 'https://ranthambhorenationalpark.in/images/easyblog_articles/148/b2ap3_medium_Wildlife-Photography-Tour-in-Ranthambore-National-Par_20200803-070952_1.jpg',
    category: ['Wildlife', 'Safari', 'Nature'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Udaipur',
    country: 'India',
    description: 'The City of Lakes offers romantic palaces, beautiful sunsets, and pleasant winter climate.',
    imageUrl: 'https://www.tourism.rajasthan.gov.in/content/dam/rajasthan-tourism/english/city/explore/221.jpg',
    category: ['Cultural', 'Historical'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Jaisalmer',
    country: 'India',
    description: 'Experience desert camping, camel safaris, and golden sand dunes in the Thar Desert.',
    imageUrl: 'https://www.tourism.rajasthan.gov.in/content/dam/rajasthan-tourism/english/city/explore/132.jpg',
    category: ['Desert', 'Adventure'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Mysore',
    country: 'India',
    description: 'Visit the magnificent Mysore Palace, beautiful gardens, and enjoy pleasant winter weather.',
    imageUrl: 'https://media2.thrillophilia.com/images/photos/000/110/596/original/1685714722_1qpoy0zzvawzvr8ar2qv68nl84fk_244.jpg?width=975&height=600',
    category: ['Cultural', 'Historical', 'City'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Hampi',
    country: 'India',
    description: 'Explore ancient ruins, boulder-strewn landscapes, and UNESCO World Heritage sites.',
    imageUrl: 'https://www.holidaymonk.com/wp-content/uploads/2020/10/Vastuchitra_Stone-Chariot-Hampi.jpg',
    category: ['Historical', 'Archaeological', 'Adventure'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Coorg',
    country: 'India',
    description: 'Known as the Scotland of India, offers coffee plantations, misty hills, and waterfalls.',
    imageUrl: 'https://mysoretocoorgcab.com/wp-content/uploads/2024/09/Coorg-tourism.jpg',
    category: ['Nature','Mountains' ],
    bestSeason: ['Winter', 'Summer', 'Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Rishikesh',
    country: 'India',
    description: 'The Yoga Capital of the World offers spiritual experiences and adventure sports.',
    imageUrl: 'https://d3sftlgbtusmnv.cloudfront.net/blog/wp-content/uploads/2024/11/Rishikesh-Cover-Photo-840x425.jpg',
    category: ['Spiritual', 'Adventure'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Varanasi',
    country: 'India',
    description: 'Experience the spiritual heart of India with ancient ghats and Ganges river rituals.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Ahilya_Ghat_by_the_Ganges%2C_Varanasi.jpg/1200px-Ahilya_Ghat_by_the_Ganges%2C_Varanasi.jpg',
    category: ['Spiritual', 'Cultural', 'Historical'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Amritsar',
    country: 'India',
    description: 'Visit the Golden Temple, witness the Wagah Border ceremony, and experience Sikh culture.',
    imageUrl: 'https://media2.thrillophilia.com/images/photos/000/152/188/original/1581765398_amritsar-3083693.jpg?width=975&height=600',
    category: ['Spiritual', 'Cultural', 'Historical'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Khajuraho',
    country: 'India',
    description: 'Famous for its intricately carved temples depicting various aspects of life and love.',
    imageUrl: 'https://www.holidify.com/images/cmsuploads/compressed/shutterstock_1032564349_20200220102557_20200220102634.jpg',
    category: ['Historical', 'Archaeological', 'Cultural'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Ajanta & Ellora',
    country: 'India',
    description: 'Ancient rock-cut caves featuring Buddhist, Hindu, and Jain monuments and paintings.',
    imageUrl: 'https://pictures.trodly.com/image/activity/3214/size-885x420/mode-crop/5d6e7827efded.jpg',
    category: ['Historical', 'Archaeological', 'Cultural'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Darjeeling',
    country: 'India',
    description: 'Famous for tea gardens, toy train, and panoramic views of Kanchenjunga mountain.',
    imageUrl: 'https://s7ap1.scene7.com/is/image/incredibleindia/2-summer-capital-of-India-darjeeling-west-bengal-city-ff?qlt=82&ts=1726643695016',
    category: ['Mountains', 'Scenic'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Ladakh',
    country: 'India',
    description: 'High-altitude desert with monasteries, lakes, and breathtaking mountain landscapes.',
    imageUrl: 'https://wanderon-images.gumlet.io/blogs/new/2023/12/leh-ladakh.jpg',
    category: ['Mountains', 'Adventure', 'Spiritual'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Kanyakumari',
    country: 'India',
    description: 'Southernmost tip of India where three seas meet, famous for sunrise and sunset views.',
    imageUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/84/41/f0/caption.jpg?w=800&h=400&s=1',
    category: ['Beach', 'Scenic', 'Spiritual'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Pondicherry',
    country: 'India',
    description: 'French colonial charm with beautiful beaches, Auroville, and spiritual centers.',
    imageUrl: 'https://www.gokitetours.com/wp-content/uploads/2025/03/best-budget-friendly-places-to-visit-in-pondicherry-950x950.webp',
    category: ['Beach', 'Cultural', 'Spiritual'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Mahabalipuram',
    country: 'India',
    description: 'UNESCO World Heritage site with ancient shore temples and rock-cut sculptures.',
    imageUrl: 'https://res.cloudinary.com/dyiffrkzh/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_center,h_400,q_auto,w_700/v1692951917/bbj/v4sc1chvycxqofsqcoms.jpg',
    category: ['Historical', 'Archaeological', 'Beach'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Bandhavgarh',
    country: 'India',
    description: 'One of the best places to spot tigers in their natural habitat with rich biodiversity.',
    imageUrl: 'https://www.naturesafariindia.com/wp-content/uploads/2021/06/Bandhavgarh-tiger-stroll.jpg',
    category: ['Wildlife', 'Safari', 'Nature'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Orchha',
    country: 'India',
    description: 'Medieval city with beautiful palaces, temples, and cenotaphs on the banks of Betwa river.',
    imageUrl: 'https://www.travelure.in/wp-content/uploads/2020/04/Raja-Bir-Singh-Deos-Cenotaph-Orchha.jpg',
    category: ['Historical', 'Cultural', 'Scenic'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Gokarna',
    country: 'India',
    description: 'Pristine beaches, laid-back vibe, and fewer crowds compared to Goa.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Delight_india.jpg',
    category: ['Beach', 'Spiritual'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Spiti Valley',
    country: 'India',
    description: 'Cold desert mountain valley with ancient monasteries and stunning landscapes.',
    imageUrl: 'https://www.holidify.com/images/bgImages/SPITI.jpg',
    category: ['Mountains', 'Adventure', 'Spiritual'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Alleppey',
    country: 'India',
    description: 'Venice of the East with backwater cruises and traditional houseboat experiences.',
    imageUrl: 'https://www.trawell.in/admin/images/upload/188158299alleppey.jpg',
    category: ['Nature'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Jodhpur',
    country: 'India',
    description: 'The Blue City famous for Mehrangarh Fort, blue houses, and desert landscapes.',
    imageUrl: 'https://www.thepinnaclelist.com/wp-content/uploads/2021/12/Jaswant-Thada-and-Mehrangarh-Fort-Jodhpur-Rajasthan-India.jpg',
    category: ['Historical', 'Cultural', 'City'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Wayanad',
    country: 'India',
    description: 'Lush green hills, wildlife sanctuaries, and spice plantations in Kerala.',
    imageUrl: 'https://s3.india.com/wp-content/uploads/2024/06/Places-to-visit-in-Wayanad.jpg##image/jpg',
    category: ['Mountains', 'Nature', 'Wildlife'],
    bestSeason: ['Winter', 'Summer', 'Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Pushkar',
    country: 'India',
    description: 'Sacred town with the only Brahma temple and famous camel fair.',
    imageUrl: 'https://static.livebooks.com/dbade8fa1a584f62a804aa32ef9b3d86/i/d66e4b521ede4b76a9e631446bd85e04/1/GCuCv726vxAVM9sgguVj4g/untitled-4.jpg',
    category: ['Spiritual', 'Cultural'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Dharamshala',
    country: 'India',
    description: 'Home to the Dalai Lama with monasteries, mountains, and Tibetan culture.',
    imageUrl: 'https://video.cgtn.com/news/7841544e3559444f7a677a4e78596a4d30637a4e31457a6333566d54/video/02d692c1b4884bba8656560e5162aed2/02d692c1b4884bba8656560e5162aed2.jpg',
    category: ['Mountains', 'Spiritual', 'Cultural'],
    bestSeason: ['Winter', 'Summer'],
    isDomestic: true,
  },
  {
    name: 'Kodaikanal',
    country: 'India',
    description: 'Princess of Hill Stations with lakes, waterfalls, and pleasant climate.',
    imageUrl: 'https://indiain360.com/wp-content/uploads/2021/03/shuttersto-71ab6709f5c509f.jpg',
    category: ['Mountains', 'Nature'],
    bestSeason: ['Winter', 'Summer', 'Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Chennai',
    country: 'India',
    description: 'Cultural capital with beautiful beaches, temples, and colonial architecture.',
    imageUrl: 'https://www.mrpilot.in/blog/wp-content/uploads/2020/01/Kapaleeshwarar-Temple-Chennai.jpg',
    category: ['Beach', 'Cultural', 'City'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Hyderabad',
    country: 'India',
    description: 'City of Pearls with historic monuments, biryani, and Charminar.',
    imageUrl: 'https://traveltoday.in/wp-content/uploads/2022/11/charminar-Hyderabad.jpg',
    category: ['Cultural', 'Historical', 'City'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Bhubaneswar',
    country: 'India',
    description: 'Temple City of India with ancient temples and rich Odia culture.',
    imageUrl: 'https://img.veenaworld.com/wp-content/uploads/2020/11/10-Tourist-Places-to-Visit-in-Bhubaneswar.jpg',
    category: ['Historical', 'Cultural', 'Spiritual'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Pune',
    country: 'India',
    description: 'Cultural capital of Maharashtra with forts, museums, and pleasant weather.',
    imageUrl: 'https://punetourism.co.in/images/places-to-visit/headers/shaniwar-wada-pune-tourism-entry-fee-timings-holidays-reviews-header.jpg',
    category: ['Cultural', 'Historical', 'City'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Ahmedabad',
    country: 'India',
    description: 'UNESCO World Heritage City with stepwells, mosques, and textile heritage.',
    imageUrl: 'https://thetravelshots.com/wp-content/uploads/2021/06/Ahmedabad-a-heritage-city.jpg',
    category: ['Cultural', 'Historical'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Lucknow',
    country: 'India',
    description: 'City of Nawabs with architectural grandeur, kebabs, and cultural richness.',
    imageUrl: 'https://www.goindigo.in/content/dam/indigov2/6e-website/destinations/lucknow/Lucknow.jpg',
    category: ['Cultural', 'Historical'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Kochi',
    country: 'India',
    description: 'Queen of Arabian Sea with Chinese fishing nets, colonial architecture, and spice markets.',
    imageUrl: 'https://irisholidays.com/keralatourism/wp-content/uploads/2021/07/places-to-visit-in-kochi.jpg',
    category: ['Cultural', 'Historical'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Madurai',
    country: 'India',
    description: 'Temple city with the magnificent Meenakshi Temple and Dravidian architecture.',
    imageUrl: 'https://th.bing.com/th/id/R.40bc9da5c30d89138d21469e288a0bc4?rik=lHdAf3Ns0EdlaQ&riu=http%3a%2f%2fs3.india.com%2ftravel%2fwp-content%2fuploads%2f2014%2f09%2fshutterstockMeenakshi-temple.jpg&ehk=Mh6%2fd2tQNq5HpP1WQ99BcV%2fXewvRb9Q%2fBOG8i5NojzU%3d&risl=&pid=ImgRaw&r=0',
    category: ['Spiritual', 'Cultural', 'Historical'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Tirupati',
    country: 'India',
    description: 'Sacred pilgrimage site with the famous Venkateswara Temple and hills.',
    imageUrl: 'https://ak.jogurucdn.com/media/image/p25/place-2016-06-9-6-0c8d32550493f0cb644c77481c5bedf3.jpg',
    category: ['Spiritual'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Nashik',
    country: 'India',
    description: 'Wine capital of India with vineyards, temples, and Godavari river.',
    imageUrl: 'https://1.bp.blogspot.com/-TymQQ19R1Dc/Xx6Bvr88IqI/AAAAAAAABsw/4LR1AxLy4NsaylemT3BNWX8-vpUAINT7wCLcBGAsYHQ/s1024/cq5dam.web.1024.576.jpeg',
    category: ['Spiritual', 'Nature'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Aurangabad',
    country: 'India',
    description: 'Gateway to Ajanta and Ellora caves with Mughal architecture and history.',
    imageUrl: 'https://aurangabadtourism.in/images/places-to-visit/header/ellora-caves-aurangabad-tourism-entry-fee-timings-holidays-reviews-header.jpg',
    category: ['Historical', 'Archaeological', 'Cultural'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Kolkata',
    country: 'India',
    description: 'Cultural capital with colonial architecture, Durga Puja, and literary heritage.',
    imageUrl: 'https://www.oyorooms.com/travel-guide/wp-content/uploads/2019/01/Victoria-Memorial.jpg',
    category: ['Cultural', 'Historical', 'City'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Bengaluru',
    country: 'India',
    description: 'Garden city with parks, palaces, tech culture, and pleasant weather.',
    imageUrl: 'https://www.asparkholidays.com/uploads/45331_palaces-heaven-on-earth-1.jpg',
    category: ['City'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Chandigarh',
    country: 'India',
    description: 'Planned city with rock garden, Sukhna lake, and modernist architecture.',
    imageUrl: 'https://static.toiimg.com/photo/66752070/01_Statues_at_Rock_Garden_Chandigarh.jpg?width=748&resize=4',
    category: ['City', 'Nature'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Dehradun',
    country: 'India',
    description: 'Gateway to Garhwal Himalayas with pleasant climate and natural beauty.',
    imageUrl: 'https://www.tripplannersindia.com/assets/blog/images/placestovisitindehradun/Dehradun.webp',
    category: ['Mountains', 'Nature'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Mussoorie',
    country: 'India',
    description: 'Queen of Hills with panoramic views, waterfalls, and colonial charm.',
    imageUrl: 'https://imgcld.yatra.com/ytimages/image/upload/v1438856096/Mussoorie_DSC_8423.jpg',
    category: ['Mountains', 'Scenic'],
    bestSeason: ['Winter', 'Summer'],
    isDomestic: true,
  },
  {
    name: 'Nainital',
    country: 'India',
    description: 'Lake district with Naini Lake, boating, and mountain views.',
    imageUrl: 'https://travelwith.in/wp-content/uploads/2023/09/nainital-lake-boating-mall-road-travelwith.jpg',
    category: ['Mountains', 'Lake', 'Scenic'],
    bestSeason: ['Winter', 'Summer'],
    isDomestic: true,
  },
  {
    name: 'Mount Abu',
    country: 'India',
    description: 'Only hill station in Rajasthan with Dilwara temples and Nakki lake.',
    imageUrl: 'https://3.bp.blogspot.com/-NTRqSTtyXR0/WK_MasevMOI/AAAAAAAAAEw/eHDzKMyUNxwdaCD9QTQ4Vyh8Rush7UeBACEw/s1600-rw/Achalgarh%2BFort.JPG',
    category: ['Mountains', 'Spiritual', 'Scenic'],
    bestSeason: ['Winter', 'Summer'],
    isDomestic: true,
  },
  {
    name: 'Kutch',
    country: 'India',
    description: 'White desert with Rann festival, handicrafts, and unique landscape.',
    imageUrl: 'https://www.tripsavvy.com/thmb/nB_VbZj6wGNXdPGYnsnLpyvm9Wc=/2122x1412/filters:fill(auto,1)/GettyImages-537000923-541774dbe2d44759815fdf0719b04685.jpg',
    category: ['Desert', 'Cultural'],
    bestSeason: ['Winter'],
    isDomestic: true,
  },
  {
    name: 'Shimla',
    country: 'India',
    description: 'Escape the summer heat in this charming hill station, known for its colonial architecture and scenic mountain views.',
    imageUrl: 'https://www.traveltoindia.org/images/shimla-featured.jpg',
    category: ['Mountains', 'Nature Walks'],
    bestSeason: ['Summer', 'Spring'],
    isDomestic: true,
  },
  {
    name: 'Ooty',
    country: 'India',
    description: 'Discover the "Queen of Hill Stations" with its beautiful tea gardens, serene lakes, and pleasant summer climate.',
    imageUrl: 'https://www.indiatravel.app/wp-content/uploads/2024/02/must-see-places-west-bengal.jpg',
    category: ['Mountains', 'Nature Walks'],
    bestSeason: ['Summer', 'Spring'],
    isDomestic: true,
  },
  {
    name: 'Manali',
    country: 'India',
    description: 'Adventure hub with paragliding, trekking, and beautiful valleys in the Himalayas.',
    imageUrl: 'https://i.pinimg.com/736x/c0/dc/df/c0dcdf0f9d9b2a276d56586c53114864.jpg',
    category: ['Mountains', 'Adventure', 'Trekking'],
    bestSeason: ['Summer'],
    isDomestic: true,
  },
  {
    name: 'Munnar',
    country: 'India',
    description: 'Tea plantations, cardamom hills, and lush greenery make it a perfect retreat in multiple seasons.',
    imageUrl: 'https://th.bing.com/th/id/OIP.2BRDsnqrjI7Dgw9uD8HJvQHaEK?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    category: ['Mountains', 'Nature'],
    bestSeason: ['Summer', 'Monsoon', 'Winter'],
    isDomestic: true,
  },
  {
    name: 'Panchgani',
    country: 'India',
    description: 'Scenic hill station with strawberry farms, table land, and cool climate.',
    imageUrl: 'https://storage.needpix.com/rsynced_images/india-1650024_1280.jpg',
    category: ['Mountains', 'Scenic'],
    bestSeason: ['Summer', 'Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Mahabaleshwar',
    country: 'India',
    description: 'Famous for strawberries, viewpoints, and pleasant weather across seasons.',
    imageUrl: 'https://www.indianholidaytrip.com/upload/static/images/Mahabaleshwar.jpg',
    category: ['Mountains', 'Scenic'],
    bestSeason: ['Summer', 'Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Dalhousie',
    country: 'India',
    description: 'Colonial hill station with pine forests, churches, and mountain views.',
    imageUrl: 'https://www.waytoindia.com/packageimages/Dalhousie-Khajjiar3.jpg',
    category: ['Mountains', 'Nature'],
    bestSeason: ['Summer'],
    isDomestic: true,
  },
  {
    name: 'McLeod Ganj',
    country: 'India',
    description: 'Little Lhasa with Tibetan monasteries, cafes, and mountain trails.',
    imageUrl: 'https://www.chinadiscovery.com/assets/images/top10/landingpage/potala-palace-850-6.jpg',
    category: ['Mountains', 'Spiritual', 'Cultural'],
    bestSeason: ['Summer'],
    isDomestic: true,
  },
  {
    name: 'Srinagar',
    country: 'India',
    description: 'Paradise on Earth with Dal Lake, houseboats, and Mughal gardens.',
    imageUrl: 'https://img.veenaworld.com/wp-content/uploads/2023/01/Best-Time-to-Visit-Srinagar-750x500.jpg?imwidth=1080',
    category: ['Lake', 'Cultural'],
    bestSeason: ['Summer'],
    isDomestic: true,
  },
  {
    name: 'Gulmarg',
    country: 'India',
    description: 'Meadow of Flowers with skiing, gondola rides, and alpine scenery.',
    imageUrl: 'https://assets.traveltriangle.com/blog/wp-content/uploads/2016/06/Gondola-ride-in-April-in-Gulmarg.jpg',
    category: ['Mountains', 'Adventure', 'Skiing'],
    bestSeason: ['Summer'],
    isDomestic: true,
  },
  {
    name: 'Pahalgam',
    country: 'India',
    description: 'Valley of Shepherds with rivers, meadows, and trekking opportunities.',
    imageUrl: 'https://www.tourmyindia.com/states/jammu-kashmir/image/aru-valley-pahalgam2.jpg',
    category: ['Mountains', 'Nature', 'Trekking'],
    bestSeason: ['Summer'],
    isDomestic: true,
  },
  {
    name: 'Sonamarg',
    country: 'India',
    description: 'Meadow of Gold with glaciers, rivers, and pristine natural beauty.',
    imageUrl: 'https://www.holidify.com/images/bgImages/SONAMARG.jpg',
    category: ['Mountains', 'Nature', 'Scenic'],
    bestSeason: ['Summer'],
    isDomestic: true,
  },
  {
    name: 'Lonavala',
    country: 'India',
    description: 'A popular monsoon getaway from Mumbai and Pune, famous for its scenic viewpoints, dams, and waterfalls.',
    imageUrl: 'https://static.wixstatic.com/media/b4110a_ea4bea85d57a4ab4a419dc3472352f1b~mv2.jpg/v1/fill/w_1000,h_583,al_c,q_85,usm_0.66_1.00_0.01/b4110a_ea4bea85d57a4ab4a419dc3472352f1b~mv2.jpg',
    category: ['Mountains', 'Hiking', 'Nature Walks'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Idukki',
    country: 'India',
    description: 'Dams, hills, and wildlife sanctuaries surrounded by lush monsoon greenery.',
    imageUrl: 'https://livekerala.com/blog/wp-content/uploads/2021/10/idukki-dam.jpg',
    category: ['Mountains', 'Nature', 'Wildlife'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Thekkady',
    country: 'India',
    description: 'Periyar Wildlife Sanctuary with boat safaris and spice plantations.',
    imageUrl: 'https://travellersworldwide.com/wp-content/uploads/2023/02/shutterstock_358672859.jpg.webp',
    category: ['Wildlife', 'Nature', 'Safari'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Valparai',
    country: 'India',
    description: 'Tea and coffee plantations with wildlife and monsoon freshness.',
    imageUrl: 'https://static-blog.treebo.com/wp-content/uploads/2023/11/Valparai_05-1024x675.jpg',
    category: ['Mountains', 'Wildlife'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Athirapally',
    country: 'India',
    description: 'Niagara Falls of India with powerful waterfalls and lush surroundings.',
    imageUrl: 'https://images.mapsofworld.com/allwonders/2015/01/Athirapally-Falls-Kerala.jpg',
    category: ['Waterfalls', 'Nature', 'Scenic'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Vagamon',
    country: 'India',
    description: 'Meadows, pine forests, and tea gardens in monsoon freshness.',
    imageUrl: 'https://static-blog.treebo.com/wp-content/uploads/2023/12/Vagamon-Pine-Forest.jpg',
    category: ['Mountains', 'Nature'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Matheran',
    country: 'India',
    description: 'Eco-sensitive hill station with toy train and monsoon mists.',
    imageUrl: 'https://www.hotelpanorama.in/wp-content/uploads/2020/01/jpg.jpg',
    category: ['Mountains', 'Nature'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Amboli',
    country: 'India',
    description: 'Western Ghats hill station with waterfalls and biodiversity.',
    imageUrl: 'https://th.bing.com/th/id/R.56f10be2971574c9ecf460d78488b899?rik=9PQhgUaBd0HWpw&riu=http%3a%2f%2fmaharashtraplanet.com%2fwp-content%2fuploads%2f2013%2f10%2fwaterfalls-at-amboli.jpg&ehk=eMs0PnCyp495NZWZK1JJxoKMEe1klYlMLA22jYGLJl0%3d&risl=&pid=ImgRaw&r=0',
    category: ['Mountains', 'Waterfalls', 'Nature'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Khandala',
    country: 'India',
    description: 'Twin hill station with Lonavala, famous for monsoon treks.',
    imageUrl: 'https://tse3.mm.bing.net/th/id/OIP.CmuZUEzqdLu4DNZpE45tGQHaFF?w=618&h=424&rs=1&pid=ImgDetMain&o=7&rm=3',
    category: ['Mountains', 'Trekking', 'Nature'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Karjat',
    country: 'India',
    description: 'Adventure destination with rivers, forts, and monsoon activities.',
    imageUrl: 'https://www.pinewoodresort.co.in/wp-content/uploads/2021/06/Bhivpuri-Waterfalls-Image-1.png',
    category: ['Adventure', 'Nature', 'Historical'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Bhandardara',
    country: 'India',
    description: 'Lake surrounded by mountains with waterfalls and greenery.',
    imageUrl: 'https://media1.thrillophilia.com/filestore/tj0lt8d6w00punei92i8b6958su5_1570446462_ArthurLake.jpg?w=1440&dpr=2',
    category: ['Lake', 'Mountains', 'Nature'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Jawhar',
    country: 'India',
    description: 'Tribal hill station with waterfalls and Warli art culture.',
    imageUrl: 'https://s3.india.com/travel/wp-content/uploads/2017/07/Jawhar-Main.jpg',
    category: ['Mountains', 'Cultural'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Malshej Ghat',
    country: 'India',
    description: 'Mountain pass with waterfalls, flamingos, and biodiversity.',
    imageUrl: 'https://www.trawell.in/admin/images/upload/86351572Nane_Ghat.jpg',
    category: ['Mountains', 'Wildlife', 'Nature'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  {
    name: 'Chikhaldara',
    country: 'India',
    description: 'Only hill station in Vidarbha with wildlife and waterfalls.',
    imageUrl: 'https://i.pinimg.com/736x/95/05/38/950538dc98e7656bf2340bbc5e2419aa.jpg',
    category: ['Mountains', 'Wildlife', 'Nature'],
    bestSeason: ['Monsoon'],
    isDomestic: true,
  },
  // --- INTERNATIONAL DESTINATIONS ---
  {
    name: 'Dubai',
    country: 'UAE',
    description: 'Experience futuristic architecture, luxury shopping, and desert safaris in pleasant winter weather.',
    imageUrl: 'https://th.bing.com/th/id/R.b4f5cc82201cf1f815a2fef33a9fe1f7?rik=zo9cJkcAIYJauA&riu=http%3a%2f%2fwww.bestdesertsafariindubai.com%2fblog%2fwp-content%2fuploads%2f2015%2f04%2fburj-al-arab-e1574079941869.jpeg&ehk=EngVrktCX6%2fuQ%2buvzQb1jrEdyPpw0vduvpT5LG%2flluI%3d&risl=&pid=ImgRaw&r=0',
    category: ['City', 'Adventure'],
    bestSeason: ['Winter', 'Autumn'],
    isDomestic: false,
  },
  {
    name: 'Kyoto',
    country: 'Japan',
    description: 'Witness the breathtaking beauty of cherry blossoms and explore ancient temples in the cultural heart of Japan.',
    imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=2070&auto=format&fit=crop',
    category: ['Cultural', 'Historical', 'City'],
    bestSeason: ['Spring', 'Autumn'],
    isDomestic: false,
  },
  {
    name: 'Paris',
    country: 'France',
    description: 'Enjoy the romantic ambiance of the City of Light with beautiful autumn colors and fewer crowds.',
    imageUrl: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/eiffel-tower-stefano-brozzi.jpg',
    category: ['City', 'Cultural'],
    bestSeason: ['Autumn', 'Spring'],
    isDomestic: false,
  },
];

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected successfully for seeder.');
  } catch (error) {
    console.error('MongoDB connection failed:', error.message);
    process.exit(1);
  }
};

const importData = async () => {
  try {
    await Destination.deleteMany();
    await Destination.insertMany(destinations);
    console.log('Data successfully imported!');
    process.exit();
  } catch (error) {
    console.error('Error with data import:', error);
    process.exit(1);
  }
};

const destroyData = async () => {
  try {
    await Destination.deleteMany();
    console.log('Data successfully destroyed!');
    process.exit();
  } catch (error) {
    console.error('Error with data destruction:', error);
    process.exit(1);
  }
};

connectDB().then(() => {
    if (process.argv[2] === '-d') {
        destroyData();
    } else {
        importData();
    }
});
