name: tripx
description: "A Flutter travel planning app that helps users organize their trips easily with features like destination ideas, trip planner, daily schedule, packing list, travel notes, and expense tracker."

# Prevent accidental publishing
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path_provider: ^2.0.15

  # SQLite Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.0

  # Utilities
  crypto: ^3.0.0

  # Uncomment/add additional packages below as needed
  # provider: ^6.1.2
  # bloc: ^8.1.4
  # flutter_bloc: ^8.1.6
  # go_router: ^14.2.7
  # http: ^1.2.2
  # dio: ^5.7.0
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # intl: ^0.19.0
  # table_calendar: ^3.1.2
  # google_maps_flutter: ^2.9.0
  # location: ^7.0.0
  # geolocator: ^13.0.1
  # image_picker: ^1.1.2
  # cached_network_image: ^3.4.1
  # lottie: ^3.1.2
  # flutter_staggered_animations: ^1.1.1
  # uuid: ^4.5.1
  # path_provider: ^2.1.4
  # permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets (uncomment and update paths as needed)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  #   - assets/data/

  # Fonts (uncomment and update as needed)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700
