name: tripx
description: "A Flutter travel planning app that helps users organize their trips easily with features like destination ideas, trip planner, daily schedule, packing list, travel notes, and expense tracker."

# Prevent accidental publishing
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8
  
  # SQLite Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.0
  
  # Additional packages for enhanced travel app functionality
  # Uncomment and add as needed:
  
  # State management
  # provider: ^6.1.2
  # bloc: ^8.1.4
  # flutter_bloc: ^8.1.6
  
  # Navigation
  # go_router: ^14.2.7
  
  # HTTP requests for travel APIs
  # http: ^1.2.2
  # dio: ^5.7.0
  
  # Additional local storage options
  shared_preferences: ^2.2.2
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  
  # Date and time handling
  # intl: ^0.19.0
  # table_calendar: ^3.1.2
  
  # Maps and location
  # google_maps_flutter: ^2.9.0
  # location: ^7.0.0
  # geolocator: ^13.0.1
  
  # Image handling
  # image_picker: ^1.1.2
  # cached_network_image: ^3.4.1
  
  # Animations
  # lottie: ^3.1.2
  # flutter_staggered_animations: ^1.1.1
  
  # Utilities
  # uuid: ^4.5.1
  # path_provider: ^2.1.4
  # permission_handler: ^11.3.1
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets for travel app
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  #   - assets/data/

  # Custom fonts for better typography
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #   
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700